dist: trusty
language: ruby
sudo: true

rvm:
  - "2.5"

env:
  matrix:
    - GPG_VERSION="2.2"

  global:
    - DEPS_BUILD_DIR="${TRAVIS_BUILD_DIR}/build"
    - DEPS_PREFIX="${TRAVIS_BUILD_DIR}/opt"
    - GPG_PREFIX="${DEPS_PREFIX}/gpg"

    - LD_RUN_PATH="${GPG_PREFIX}/lib"

    - PATH="${GPG_PREFIX}/bin:${PATH}"

    # Many of these are supported only in few GPG components, hence bunch of
    # harmless warnings typically shows up.
    - >
      GPG_CONFIGURE_OPTS="--disable-doc --enable-pinentry-curses
      --disable-pinentry-emacs --disable-pinentry-gtk2 --disable-pinentry-gnome3
      --disable-pinentry-qt --disable-pinentry-qt4 --disable-pinentry-qt5
      --disable-pinentry-tqt --disable-pinentry-fltk
      --prefix=${GPG_PREFIX}
      --with-libgpg-error-prefix=${GPG_PREFIX}
      --with-libassuan-prefix=${GPG_PREFIX}
      --with-libgpg-error-prefix=${GPG_PREFIX}
      --with-libgcrypt-prefix=${GPG_PREFIX}
      --with-libassuan-prefix=${GPG_PREFIX}
      --with-ksba-prefix=${GPG_PREFIX}
      --with-npth-prefix=${GPG_PREFIX}"

cache:
  bundler: true
  directories:
    - opt

before_install:
  - mkdir -p ${DEPS_PREFIX}
  - pushd ci
  - >
    ./install_gpg_all.sh "${GPG_VERSION}"
    --build-dir "${DEPS_BUILD_DIR}/gpg"
    --configure-opts "${GPG_CONFIGURE_OPTS}"
    --folding-style travis
  - popd
  - gem install bundler -v "~> 1.16"

after_install:
  - bundle update

before_script:
  - bundle exec rake pgp_keys:generate
  - bundle exec rake pgp_keys:list
