dist: bionic
language: ruby

rvm:
  - "2.7"
  - "2.6"
  - "2.5"
  - "2.4"
  - "2.3"
  - "ruby-head"

env:
  matrix:
    - GPG_VERSION="2.2"

  global:
    - DEPS_PREFIX="${TRAVIS_BUILD_DIR}/opt"
    - GPG_PREFIX="${DEPS_PREFIX}/gpg"

    - LD_RUN_PATH="${GPG_PREFIX}/lib"

    - PATH="${GPG_PREFIX}/bin:${PATH}"

    # Many of these are supported only in few GPG components, hence bunch of
    # harmless warnings typically shows up.
    - >
      GPG_CONFIGURE_OPTS="--disable-doc --enable-pinentry-curses
      --disable-pinentry-emacs --disable-pinentry-gtk2 --disable-pinentry-gnome3
      --disable-pinentry-qt --disable-pinentry-qt4 --disable-pinentry-qt5
      --disable-pinentry-tqt --disable-pinentry-fltk
      --prefix=${GPG_PREFIX}
      --with-libgpg-error-prefix=${GPG_PREFIX}
      --with-libassuan-prefix=${GPG_PREFIX}
      --with-libgpg-error-prefix=${GPG_PREFIX}
      --with-libgcrypt-prefix=${GPG_PREFIX}
      --with-libassuan-prefix=${GPG_PREFIX}
      --with-ksba-prefix=${GPG_PREFIX}
      --with-npth-prefix=${GPG_PREFIX}"

cache:
  bundler: true
  directories:
    - opt

before_install:
  - mkdir -p ${DEPS_PREFIX}
  - pushd ci/gpg
  - >
    [ -d "${GPG_PREFIX}" ] ||
    ./install_gpg_all.sh
    --suite-version "${GPG_VERSION}"
    --configure-opts "${GPG_CONFIGURE_OPTS}"
    --folding-style travis
  - popd

install:
  - bundle install --jobs=3 --retry=3 --path=${BUNDLE_PATH:-vendor/bundle}
  - bundle update --jobs=3 --retry=3

before_script:
  - gpg --version
  - bundle exec rake pgp_keys:generate
  - bundle exec rake pgp_keys:list

matrix:
  include:
    - gemfile: ci/gemfiles/rspec-3.7.gemfile
      rvm: 2.5
    - gemfile: ci/gemfiles/rspec-3.6.gemfile
      rvm: 2.5
    - gemfile: ci/gemfiles/rspec-3.5.gemfile
      rvm: 2.5
    - gemfile: ci/gemfiles/rspec-3.4.gemfile
      rvm: 2.5
  allow_failures:
    - rvm: ruby-head
